spring:
  application:
    name: Spring-Data-JPA-Homework
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa
    username: postgres
    password: rosella22
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        spring:
          jpa:
            show-sql=true:
